//script generated by SiteXpert (www.xtreeme.com)
//Copyright(C) 1998-2003 Xtreeme GmbH
function addLoadHandler(lh){
if(lh){
if(!document.loadHandlers){
document.loadHandlers=new Array()
document.loadHandlers[0]=lh
document.lastLoadHandler=0}
else{
document.lastLoadHandler++
document.loadHandlers[document.lastLoadHandler]=lh}}}
addLoadHandler('p11')
addLoadHandler(window.onload)
window.onload=initializeAll
function p15(){return true;}
window.onerror=p15
function p01(n01){
if(!n01.id)return-1
end=n01.id.indexOf("SXE")
if(end==-1)
return-1
return parseInt(n01.id.substring(1,end))}
function getIndexNS(el){
var i
ind=-1
for(i=0;i<document.layers.length;i++){
var n01=document.layers [i]
if(n01==el){
ind=i
break}}
return ind}
function setPosition(){
document.layers [firstItem].pageY=document.TP.pageY+15
document.layers [firstItem].pageX=document.TP.pageX
nextY=document.layers [firstItem].pageY+document.layers [firstItem].document.height
var i
for(i=firstItem+1;i<=lastItem&&i<document.layers.length;i++){
n01=document.layers [i]
if(n01.visibility !="hide"){
n01.pageY=nextY
nextY+=n01.document.height}
n01.pageX=document.TP.pageX}
bel=document.layers["below"]
if(bel){bel.pageY=nextY;bel.pageX=document.TP.pageX;}}
function p11(){
if(n03)return
if(IE4){
firstItem=getIndexIE(SXR)
lastItem=getIndexIE(eval(li))}
if(NS4){
firstItem=getIndexNS(document.SXR)
lastItem=getIndexNS(eval("document."+li))
for(i=firstItem;i<=lastItem&&i<document.layers.length;i++)
document.layers [i].visibility="show"
setPosition()}
var nextind=0
var sxpind=0
var state
var i
if(nDays>0){
cks=document.cookie.split(';')
for(i=0;i<cks.length;i++){
if(cks [i].indexOf("sxtree")!=-1)state=cks[i].substring(cks[i].indexOf("=")+1)}}
if(NS4){
for(i=0;i<document.layers.length;i++){
n01=document.layers [i]
ii=p01(n01)
if(!state || nDays==0 || document.cookie.indexOf("sxpossaved")==-1){
if((n01.id.indexOf("SXC")!=-1&&ii==n04)|| ii>n04)
n01.visibility="hide"}
else if(n01.id.indexOf("SXP")!=-1){
var bset=false
if(i>=nextind&&state.substr(sxpind,1)=="0"){
var elid=n01.id.substring(0,n01.id.indexOf("SXP"))
nextind=p06NS(elid)
bset=true}
if(!bset&&i>=nextind){
n01.document.images ["M"+n01.id].src=imf1
if(n02&&n01.document.images ["N"+n01.id].src&&n01.document.images ["N"+n01.id].src.indexOf('i2.gif')!=-1)n01.document.images ["N"+n01.id].src=imf3}
sxpind++}}
setPosition()}
else{
tempColl=document.all.tags("DIV")
for(i=0;i<tempColl.length;i++){
el=tempColl(i)
if(el.id&&el.id.indexOf('SX')!=-1){
ii=p01(el)
if(!state || nDays==0 || document.cookie.indexOf("sxpossaved")==-1){
if((el.id.indexOf("SXC")!=-1&&ii==n04)|| ii>n04)
el.style.display="none"}
else if(el.id.indexOf("SXP")!=-1){
var bset=false
if(i>=nextind&&state.substr(sxpind,1)=="0"){
var elid=el.id.substring(0,el.id.indexOf("SXP"))
nextind=p06IE(elid)
bset=true}
if(!bset&&i>=nextind){
document.images ["M"+el.id].src=imf1
if(n02&&document.images ["N"+el.id].src&&document.images ["N"+el.id].src.indexOf('i2.gif')!=-1)document.images ["N"+el.id].src=imf3}
sxpind++}}}}
doAutoSync()}
function p06(elm,lev,el){
if(!elm){elm="I"+lev+"SXE"+el;}
var rv
if(!ver4||n03)return rv
if(IE4)
rv=p06IE(elm)
else
rv=p06NS(elm)
p10V4()
return rv}
function p03IE(n01,image,image2){
if(n01.style.display=="none"){
n01.style.display="block"
if(image)
image.src=imf1
if(image2&&image2.src&&image2.src.indexOf('i2.gif')!=-1)
image2.src=imf3}
else{
n01.style.display="none"
if(image)
image.src=imf0
if(image2&&image2.src&&image2.src.indexOf('i3.gif')!=-1)
image2.src=imf2}}
function p06IE(el){
n01=eval(el+"SXC")
image=document.images["M"+el+"SXP"]
var image2=null
if(n02)
image2=document.images["N"+el+"SXP"]
var bShow=(n01.style.display=="none")
p03IE(n01,image,image2)
var ind=getIndexIE(n01)+1
tempColl=document.all.tags("DIV")
while(ind !=-1&&ind<tempColl.length){
var retVal=0
elem=tempColl(ind)
if(elem.id&&elem.id.indexOf('SX')!=-1){
var tci=p01(elem)
var tii=p01(n01)
var bfold=(elem.id.indexOf("SXP")!=-1)
if(tci==(tii+1)){
if(bfold)
retVal=3
else
retVal=1}
else if(tci>(tii+1))
retVal=2
else if(tci==tii&&!bfold)
retVal=3
else
break
if(bShow){
if(retVal==3)
p03IE(elem,null,null)}
else{
elem.style.display="none"
if(bfold){
document.images["M"+elem.id].src=imf0
if(n02&&document.images["N"+elem.id].src&&document.images["N"+elem.id].src.indexOf('i3.gif')!=-1)document.images["N"+elem.id].src=imf2}}}
ind++}
return ind}
function p03NS(n01,image,image2){
if(n01.visibility=="hide"){
n01.visibility="show"
if(image)
image.src=imf1
if(image2&&image2.src&&image2.src.indexOf('i2.gif')!=-1)
image2.src=imf3}
else{
n01.visibility="hide"
if(image)
image.src=imf0
if(image2&&image2.src&&image2.src.indexOf('i3.gif')!=-1)
image2.src=imf2}}
function p06NS(el){
n01=eval("document."+el+"SXC")
image=eval("document."+el+"SXP.document.images['M'+el+'SXP']")
var image2=null
if(n02)
image2=eval("document."+el+"SXP.document.images['N'+el+'SXP']")
var bShow=(n01.visibility=="hide")
p03NS(n01,image,image2)
var ind=getIndexNS(n01)+1
while(ind !=-1&&ind<document.layers.length){
var retVal=0
elem=document.layers [ind]
var tci=p01(elem)
var tii=p01(n01)
var bfold=(elem.id.indexOf("SXP")!=-1)
if(tci==(tii+1)){
if(bfold)
retVal=3
else
retVal=1}
else if(tci>(tii+1))
retVal=2
else if(tci==tii&&!bfold)
retVal=3
else
break
if(bShow){
if(retVal==3)
p03NS(elem,null)}
else{
elem.visibility="hide"
if(bfold){
elem.document.images ['M'+elem.id].src=imf0
if(n02&&elem.document.images ['N'+elem.id].src&&elem.document.images ['N'+elem.id].src.indexOf('i3.gif')!=-1)
elem.document.images ['N'+elem.id].src=imf2}}
ind++}
setPosition()
return ind}
function onExpandAll(){
var i
newSrc=imf1
if(NS4){
for(i=firstItem;i<=lastItem&&i<document.layers.length;i++){
n01=document.layers [i]
if(n01.id.indexOf("SXP")!=-1){
n01.document.images ["M"+n01.id].src=newSrc
if(n02&&n01.document.images ["N"+n01.id].src&&n01.document.images ["N"+n01.id].src.indexOf('i2.gif')!=-1)
n01.document.images ["N"+n01.id].src=imf3}
n01.visibility="show"}
setPosition()}
else{
divColl=document.all.tags("DIV")
for(i=firstItem;i<=lastItem&&i<divColl.length;i++){
el=divColl(i)
if(el.id&&el.id.indexOf('SX')!=-1){
el.style.display="block"
if(el.id.indexOf("SXP")!=-1){
document.images ["M"+el.id].src=newSrc
if(n02&&document.images ["N"+el.id].src&&document.images ["N"+el.id].src.indexOf('i2.gif')!=-1)
document.images ["N"+el.id].src=imf3}}}}
p10V4()}
function onCollapseAll(){
var i
newSrc=imf0
if(NS4){
for(i=firstItem;i<=lastItem&&i<document.layers.length;i++){
n01=document.layers [i]
if(n01.id.indexOf("SXP")!=-1){
n01.document.images ["M"+n01.id].src=newSrc
if(n02&&n01.document.images ["N"+n01.id].src&&n01.document.images ["N"+n01.id].src.indexOf('i3.gif')!=-1)
n01.document.images ["N"+n01.id].src=imf2}
if(n01.id.indexOf("SXC")!=-1 || p01(n01)>0)
n01.visibility="hide"}
setPosition()}
else{
divColl=document.all.tags("DIV")
for(i=firstItem;i<=lastItem&&i<divColl.length;i++){
el=divColl(i)
if(el.id.indexOf("SXP")!=-1){
document.images ["M"+el.id].src=newSrc
if(n02&&document.images ["N"+el.id].src&&document.images ["N"+el.id].src.indoxOf('i3.gif')!=-1)
document.images ["N"+el.id].src=imf2}
if(el.id.indexOf("SXC")!=-1 || p01(el)>0)
el.style.display="none"}}
p10V4()}
function p09(date){
var base=new Date(0)
var off=base.getTime()
if(off>0)
date.setTime(date.getTime()-off)}
function p10(){}
function p10V4(){
var i
if(nDays>0&&!n03){
var now=new Date()
p09(now)
now.setTime(now.getTime()+nDays*24*60*60*1000)
var strnow=now.toGMTString()
var ckstr=""
var str
ind=-1
if(NS4){
for(i=firstItem;i<=lastItem&&i<document.layers.length;i++){
var n01=document.layers [i]
if(n01.id.indexOf("SXP")!=-1){
var sxc=eval("document."+n01.id.substring(0,n01.id.indexOf("SXP"))+"SXC")
if(sxc.visibility=="hide")
ckstr+="0"
else
ckstr+="1"}}}
else{
divColl=document.all.tags("DIV")
for(i=firstItem;i<=lastItem&&i<divColl.length;i++){
var n01=divColl(i)
if(n01.id.indexOf("SXP")!=-1){
var sxc=eval(n01.id.substring(0,n01.id.indexOf("SXP"))+"SXC")
if(sxc.style.display=="none")
ckstr+="0"
else
ckstr+="1"}}}
document.cookie="sxtree="+ckstr+"; expires="+strnow
document.cookie="sxpossaved=true; expires="+strnow}
return true}
function getParentNS(el){
var els=document.layers
var i
var divs=new Array
for(i=0;i<els.length;i++){
var cel=els[i]
if(cel.id&&cel.id.indexOf("SXP")!=-1){
var lev=p01(cel)
divs[lev]=cel
if(el.id==cel.id){
if(lev==0){return null;}else{return divs[lev-1];}}}}
return null}
function p12NS(el){
var retval=0
if(!el)return
if(el.id&&el.id.indexOf("SXP")!=-1){
p12NS(getParentNS(el))
var ch=document.layers[el.id.substring(0,el.id.indexOf("SXP"))+"SXC"]
if(ch&&ch.visibility=="hide")p06NS(el.id.substring(0,el.id.indexOf("SXP")))
retval=1}
else if(el.id&&el.id.indexOf("SXC")!=-1){
p12NS(document.layers[el.id.substring(0,el.id.indexOf("SXC"))+"SXP"])
retval=1}
return retval}
function ReplaceAll(str,src,trg){
var s=str
var start=0
while(true){
var ind=s.indexOf(src,start)
if(ind==-1){
break}
s=s.substring(0,ind)+trg+s.substr(ind+src.length)
start=ind+trg.length}
return s}
function p13(url){
var newUrl=unescape(url.toLowerCase())
newUrl=ReplaceAll(newUrl,'\\', '/')
newUrl=ReplaceAll(newUrl,'%20',' ')
var ind=newUrl.indexOf('index.')
var ind2=newUrl.indexOf('#')
if((ind2<ind || ind==-1)&&ind2 !=-1)ind=ind2
if(ind!=-1)newUrl=newUrl.substr(0,ind)
if(newUrl.length>0&&newUrl.substr(newUrl.length-1,1)=="/")newUrl=newUrl.substr(0,newUrl.length-1)
return newUrl}
function synchronizeNS(url){
var lurl=p13(url.href)
var els=document.layers
var i
for(i=0;i<els.length;i++){
var j
var aels=els[i].document.links
for(j=0;j<aels.length;j++){
if(lurl==p13(aels[j].href)&&syncEl!=aels[j]){
if(p12NS(els[i])){
syncEl=aels[j]
break}}}}}
function p12IE(el){
var retval=0
if(!el)return
if(el.id&&el.id.indexOf("SXP")!=-1){
if(el.par!='root')p12IE(eval(el.par))
var ch=eval(el.id.substring(0,el.id.indexOf("SXP"))+"SXC")
if(ch&&ch.style.display=="none")p06(el.id.substring(0,el.id.indexOf("SXP")))
retval=1}
else if(el.id&&el.id.indexOf("SXC")!=-1){
p12IE(eval(el.par))
retval=1}
else{
if(el.id&&el.id.indexOf("SXR")!=-1)retval=1
if(p12IE(el.parentElement))retval=1}
return retval}
function synchronizeIE(url){
var lurl=p13(url.href)
var els=document.all.tags("a")
var i
for(i=0;i<els.length;i++){
if(lurl==p13(els[i].href)&&syncEl!=els[i]){
if(p12IE(els[i].parentElement?els[i].parentElement:els[i].parentNode)){
if(syncEl){syncEl.style.backgroundColor=document.body.bgColor?document.body.bgColor:'';syncEl.innerHTML=syncEl.getAttribute('oldCode');}
els[i].style.backgroundColor=syncBgColor
els[i].setAttribute('oldCode',els[i].innerHTML)
els[i].innerHTML='['+els[i].innerHTML+']'
syncEl=els[i]
break}}}}
function synchronize(url){
if(IE4){synchronizeIE(url);}else{synchronizeNS(url);}}
function initializeAll(){
var i
var l=document.lastLoadHandler
document.lastLoadHandler=-1
for(i=0;i<=l;i++){
var h=document.loadHandlers[i]
if(typeof(h)!='function'){
var bPar=(h.indexOf('(')==-1)
eval(h+(bPar ? '();' : ';'))}
else{
h()}}}
