//script generated by SiteXpert (www.xtreeme.com)
//Copyright(C) 1998-2003 Xtreeme GmbH
function addLoadHandler(lh){
if(lh){
if(!document.loadHandlers){
document.loadHandlers=new Array()
document.loadHandlers[0]=lh
document.lastLoadHandler=0}
else{
document.lastLoadHandler++
document.loadHandlers[document.lastLoadHandler]=lh}}}
addLoadHandler('p11')
addLoadHandler(window.onload)
window.onload=initializeAll
function p15(){return true;}
window.onerror=p15
function p01(n01){
if(!n01.id)return-1
var end=n01.id.indexOf("SXE")
if(end==-1 || n01.id.indexOf("PH")!=-1)return-1
return parseInt(n01.id.substring(1,end))}
function p03(n01,image,image2){
if(n01.style.display=="none"){
n01.style.display="block"
if(image)image.src=imf1
if(image2&&image2.src&&image2.src.indexOf('i2.gif')!=-1)image2.src=imf3}
else{
n01.style.display="none"
if(image)image.src=imf0
if(image2&&image2.src&&image2.src.indexOf('i3.gif')!=-1)image2.src=imf2}}
function p06(elm,lev,el){
if(!elm){elm="I"+lev+"SXE"+el;}
var n01=document.getElementById(elm+"SXC")
var image=document.images ["M"+elm+"SXP"]
var image2=null
if(n02)image2=document.images ["N"+elm+"SXP"]
var bShow=(n01.style.display=="none")
var fold=document.getElementById(elm+'SXP')
p03(n01,image,image2)
var elem=n01.nextSibling
var tii=p01(n01)
while(elem){
var retVal=0
var tci=p01(elem)
if(tci!=-1){
var bfold=(elem.id.indexOf("SXP")!=-1)
if(tci==(tii+1)){
if(bfold)retVal=3
else
retVal=1}
else if(tci>(tii+1))retVal=2
else if(tci==tii&&!bfold)retVal=3
else break
if(bShow){
if(retVal==3)p03(elem,null,null)}
else{
elem.style.display="none"
if(bfold){
document.images["M"+elem.id].src=imf0
if(n02&&document.images["N"+elem.id].src&&document.images["N"+elem.id].src.indexOf('i3.gif')!=-1)document.images["N"+elem.id].src=imf2}}}
elem=elem.nextSibling}
return elem}
function onExpandAll(){
var newSrc=imf1
var divColl=document.getElementsByTagName("DIV")
var i
for(i=0;i<divColl.length;i++){
el=divColl[i]
if(el.id&&el.id.indexOf('SX')!=-1){
el.style.display="block"
if(el.id.indexOf("SXP")!=-1){
document.images["M"+el.id].src=newSrc
if(n02&&document.images["N"+el.id].src&&document.images["N"+el.id].src.indexOf('i2.gif')!=-1)document.images["N"+el.id].src=imf3}}}}
function onCollapseAll(){
var newSrc=imf0
var divColl=document.getElementsByTagName("DIV")
var i
for(i=0;i<divColl.length;i++){
var el=divColl[i]
if(el.id&&el.id.indexOf('SX')!=-1){
if(el.id.indexOf("SXP")!=-1){
document.images["M"+el.id].src=newSrc
if(n02&&document.images["N"+el.id].src&&document.images["N"+el.id].src.indexOf('i3.gif')!=-1)document.images["N"+el.id].src=imf2}
if(el.id.indexOf("SXC")!=-1||p01(el)>0)el.style.display="none"}}}
function p10(){
return true}
function p11(){
if(n03)return
var nextFolder=null
var bIgnoredFolder=true
var sxpind=0
var state
var i
var tempColl=document.getElementsByTagName("DIV")
for(i=0;i<tempColl.length;i++){
var el=tempColl[i]
if(el.id&&el.id.indexOf('SX')!=-1){
var ii=p01(el)
if(el==nextFolder){bIgnoredFolder=true;}
if(!state||nDays==0||document.cookie.indexOf("sxpossaved")==-1){
if((el.id.indexOf("SXC")!=-1&&ii==n04)||ii>n04)el.style.display="none"}
else if(el.id.indexOf("SXP")!=-1){
var bset=false
if(bIgnoredFolder&&state.substr(sxpind,1)=="0"){
var elid=el.id.substring(0,el.id.indexOf("SXP"))
nextFolder=p06(elid)
bIgnoredFolder=false
bset=true}
if(!bset&&bIgnoredFolder){
document.images["M"+el.id].src=imf1
if(n02&&document.images["N"+el.id].src&&document.images["N"+el.id].src.indexOf('i2.gif')!=-1)document.images["N"+el.id].src=imf3}
sxpind++}}}}
function p12(el){
var retval=0
if(!el)return
if(el.id&&el.id.indexOf("SXP")!=-1){
p12(document.getElementById(el.getAttribute('par')))
var ch=document.getElementById(el.id.substring(0,el.id.indexOf("SXP"))+"SXC")
if(ch&&ch.style.display=="none")p06(el.id.substring(0,el.id.indexOf("SXP")))
retval=1}
else if(el.id&&el.id.indexOf("SXC")!=-1){
p12(document.getElementById(el.getAttribute('par')))
retval=1}
else{
if(el.id&&el.id.indexOf("SXR")!=-1)retval=1
if(p12(el.parentElement?el.parentElement:el.parentNode))retval=1}
return retval}
function initializeAll(){
var i
var l=document.lastLoadHandler
document.lastLoadHandler=-1
for(i=0;i<=l;i++){
var h=document.loadHandlers[i]
if(typeof(h)!='function'){
var bPar=(h.indexOf('(')==-1)
eval(h+(bPar ? '();' : ';'))}
else{
h()}}}
